FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD psjs1.jar /opt/psjs1/
EXPOSE 8080
WORKDIR /opt/psjs1/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "psjs1.jar"]
